Models/UsuarioAplicacao.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alura_AspNet_Identity.Models
{
    public class UsuarioAplicacao : IdentityUser
    {
        public string NomeCompleto { get; set; }
    }
}

ViewModels/AccountLoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alura_AspNet_Identity.ViewModels
{
    public class AccountLoginViewModel
    {
        
        
        /*[Required]
        [EmailAddress]
        public string Email { get; set; }*/

        [Required]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Continuar logado")]
        public bool KeepLogedIn { get; set; }
    }
}

ViewModels/ContaRegistrarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alura_AspNet_Identity.ViewModels
{
    public class ContaRegistrarViewModel
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        [Display (Name = "Nome Completo")]
        public string NomeCompleto { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
    }
}

ViewModels/CreateTopicViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Alura_AspNet_Identity.ViewModels
{
    public class CreateTopicViewModel
    {
        public string Title { get; set; }
        public string Content { get; set; }
    }
}

Controllers/AdmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alura_AspNet_Identity.Controllers
{
    [Authorize]
    public class AdmController : Controller
    {
        // GET: Adm
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ContaController.cs
using Alura_AspNet_Identity.Models;
using Alura_AspNet_Identity.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;

namespace Alura_AspNet_Identity.Controllers
{
    public class ContaController : Controller
    {

        private UserManager<UsuarioAplicacao> _userManager;
        public UserManager<UsuarioAplicacao> UserManager
        {
            get
            {
                if (_userManager == null)

                {
                    var contextOwin = HttpContext.GetOwinContext();
                    _userManager = contextOwin.GetUserManager<UserManager<UsuarioAplicacao>>();
                }
                return _userManager;
            }
            set
            {
                _userManager = value;
            }
        }
        private SignInManager<UsuarioAplicacao, string> _signInManager;
        public SignInManager<UsuarioAplicacao, string> SignInManager
        {
            get
            {
                if (_signInManager == null)
                {
                    var contextOwin = HttpContext.GetOwinContext();
                    _signInManager = contextOwin.GetUserManager<SignInManager<UsuarioAplicacao, string>>();
                }
                return _signInManager;
            }
            set
            {
                _signInManager = value;
            }
        }
        public IAuthenticationManager AuthenticationManager
        {
            get
            {
                var contextOwin = Request.GetOwinContext();
                return contextOwin.Authentication;
            }
        }

        // GET: Conta
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Registrar(ContaRegistrarViewModel modelo)
        {
            if (ModelState.IsValid)
            {
                var novoUsuario = new UsuarioAplicacao();

                novoUsuario.Email = modelo.Email;
                novoUsuario.UserName = modelo.UserName;
                novoUsuario.NomeCompleto = modelo.NomeCompleto;

                var checkUser = await UserManager.FindByEmailAsync(modelo.Email);
                var userExist = checkUser != null;

                var resultado = await UserManager.CreateAsync(novoUsuario, modelo.Senha);

                if (resultado.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    AdicionaErros(resultado);
                }

            }

            // Alguma coisa deu errada
            return View(modelo);
        }

        public async Task<ActionResult> Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Login(AccountLoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Realizar Login pelo Identity

                var user = await UserManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    var signInResult = await SignInManager.PasswordSignInAsync(
                        user.UserName,
                        model.Password,
                        isPersistent: model.KeepLogedIn,
                        shouldLockout: true);

                    switch (signInResult)
                    {
                        case SignInStatus.Success:
                            return RedirectToAction("Index", "Home");
                        case SignInStatus.LockedOut:
                            var correctPassword = await UserManager.CheckPasswordAsync(user, model.Password);
                            if (correctPassword)
                            {
                                ModelState.AddModelError("", "Login attempts exceeded, try again later.");
                                break;
                            }
                            else
                                return InvalidPasswordOrUser();
                        default:
                            return InvalidPasswordOrUser();
                    }
                }
                else if (user == null)
                    return InvalidPasswordOrUser();
            }

            // Algo de errado aconteceu
            return View(model);
        }


        [HttpPost]
        public ActionResult Logoff()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        private ActionResult InvalidPasswordOrUser()
        {
            ModelState.AddModelError("", "Invalid user or password");
            return View("Login");
        }

        private void AdicionaErros(IdentityResult resultado)
        {
            foreach (var erro in resultado.Errors)
                ModelState.AddModelError("", erro);
        }


    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alura_AspNet_Identity.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/TopicController.cs
using Alura_AspNet_Identity.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alura_AspNet_Identity.Controllers
{
    public class TopicController : Controller
    {
        // GET: Topic
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(CreateTopicViewModel model)
        {
            return View();
        }

    }
}

Views/Adm/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

Views/Conta/Login.cshtml
@model Alura_AspNet_Identity.ViewModels.AccountLoginViewModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("", new { @class = "text-danger" })

    @Html.EditorForModel()

    <hr />

    <input type="submit" value="Login" />

}

Views/Conta/Registrar.cshtml
@model Alura_AspNet_Identity.ViewModels.ContaRegistrarViewModel

@{
    ViewBag.Title = "Registrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar</h2>

@using (Html.BeginForm())
{
    <h3>Registre-se</h3>
    <hr/>

    @Html.ValidationSummary("", new { @class = "text-danger" })

    @Html.EditorForModel()

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">    

            <input type="submit" value="Registrar" class="btn btn-default" />
    
        </div>

    
    </div>



}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ByteBank Forum", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Criar novo tópico", "Create", "Topic")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("Logoff", "Conta", FormMethod.Post, new { id = "form_logoff" })) { }
                        <li><p class="navbar-text">@User.Identity.GetUserName()</p></li>
                        <li><a href="javascript: document.getElementById('form_logoff').submit()">Logoff</a></li>
                    }
                    else
                    {

                        <li>@Html.ActionLink("Registrar", "Registrar", "Conta")</li>
                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>

                    }
                </ul>




                </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Topic/Create.cshtml
@model Alura_AspNet_Identity.ViewModels.CreateTopicViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("", new { @class = "text-danger"})

    @Html.EditorForModel()

    <hr/>

    <input type="submit" value="Criar Tópico" />
}